---
name: Check Pull Request
permissions:
  security-events: write
  pull-requests: write
  packages: read
  actions: read
  contents: read
  deployments: write
  issues: write
  checks: write
  statuses: write # Used by CM to mark commit status
on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
# Ensures that only one deploy task per branch/environment will run at a time.
concurrency:
  group: action-${{ github.ref }}
  cancel-in-progress: true

jobs:
  danger_ci:
    name: Danger CI
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      # - name: Install Swiftlint
      #   run: brew install swiftlint
      #   env:
      #     HOMEBREW_NO_AUTO_UPDATE: 1
      
      - name: Install Danger-Swift
        run: brew install danger/tap/danger-swift
        env:
          HOMEBREW_NO_AUTO_UPDATE: 1

      - name: Verify Danger-Swift installation
        run: which danger-swift
      
      - name: Danger Swift
        run: danger-swift ci
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    continue-on-error: false

    

